# Generated by Django 5.2.8 on 2025-11-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bid",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.RenameField(
            model_name="listing",
            old_name="starting_bid",
            new_name="start_bid",
        ),
    ]
