# Generated by Django 5.2.8 on 2025-11-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_delete_bid_delete_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watched_by", to="auctions.listing"
            ),
        ),
    ]
