# Generated by Django 5.2.8 on 2025-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="start_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
